# Generated by Django 5.0.1 on 2024-01-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='debt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='задолженность перед поставщиком'),
        ),
    ]
